server:
  port: 4004

auth:
  service:
    url: ${AUTH_SERVICE_URL}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - JwtValidation

            - id: auth-service-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api/auth/**


            - id: user-service-route
              uri: http://auth-service:4005
              predicates:
                  - Path=/api/user/**
              filters:
                  - JwtValidation