services:

  db:
    container_name: analytics-db
    image: postgres:14.22-alpine3.23

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics-service
      PGDATA: /data/postgres

    volumes:
      - analytics-db:/data/postgres

    ports:
      - "5335:5432"

    networks:
      - patient-network

    restart: unless-stopped


  analytics-service:
    container_name: analytics-service

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "4002:4002"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/patient-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      BILLING_SERVICE_ADDRESS: analytics-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


    depends_on:
      - db

    networks:
      - patient-network

    restart: unless-stopped


networks:
  patient-network:
    external: true


volumes:
  analytics-db: