spring.application.name=patient-service

spring.datasource.url=jdbc:postgresql://localhost:5332/patient-service
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

