services:

  db:
    container_name: billing-db
    image: postgres:14.22-alpine3.23

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billing-service
      PGDATA: /data/postgres

    volumes:
      - billing-db:/data/postgres

    ports:
      - "5333:5432"

    networks:
      - patient-network

    restart: unless-stopped


  billing-service:
    container_name: billing-service

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      # Spring Boot HTTP
      - "4001:4001"

      # gRPC
      - "9001:9001"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/billing-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

    depends_on:
      - db

    networks:
      - patient-network

    restart: unless-stopped


networks:
  patient-network:
    external: true


volumes:
  billing-db: